name: Update Whale Ranking

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  whalewatching:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up python environment
      uses: actions/setup-python@v2.3.1
      with:
        python-version: "3.10"
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Update whale ranking
      run: |
        python whalewatching.py
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: whalewatching.json
